# Generated by Django 2.1.3 on 2018-11-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20181127_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-updated', 'content']},
        ),
    ]
